"locales.create-table" = "CREATE TABLE IF NOT EXISTS locales(id BIGSERIAL PRIMARY KEY, lang varchar(6) NOT NULL, code varchar(255) NOT NULL, message TEXT NOT NULL)"
"locales.create-index-code-lang" = "CREATE UNIQUE INDEX idx_locales_code_lang ON locales (code, lang)"
"locales.create-index-code" = "CREATE INDEX idx_locales_code ON locales (code)"
"locales.create-index-lang" = "CREATE INDEX idx_locales_lang ON locales (lang)"
"locales.select-all" = "SELECT lang, code, message FROM locales"
"locales.select-id" = "SELECT COUNT(*) FROM locales WHERE code = $1 AND message = $2"
"locales.update" = "UPDATE locales SET message = $2 WHERE id = $1"
"locales.insert" = "INSERT INTO locales(lang, code, message) VALUES($1, $2, $3)"
"locales.delete" = "DELETE FROM locales WHERE id = $1"
