[package]
name = "h2o"
version = "0.1.0"
authors = ["Jeremy Zheng <jitang.zheng@gmail.com>"]

[dependencies]
redis = "0.8.0"
postgres = "0.14.2"
docopt = "0.8.1"
mustache = "0.8.0"
serde = "1.0.10"
serde_derive = "1.0.10"
serde_bytes = "0.10.1"
serde_json = "1.0.2"
serde_yaml = "0.7.1"
