secret: zeelohV6Huliem8Lahb2oe9ziechahga
database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/h2o_dev
  user: postgres
  password:
  validationQuery: SELECT 1
  maxSize: 32
  maxWaitForConnection: 1s
  properties:
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level: INFO
  loggers:
    com.github.kapmahc: DEBUG
