# config/app.yml for rails-settings-cached
defaults: &defaults
  languages:
    en: English
    zh-CN: 简体中文
    zh-TW: 繁體中文
  zh-CN:
    nav:
      header:
        - {label: '下拉1', items: [{href: "/forum/topics/1", label: "菜单11"}, {href: "/forum/topics/1", label: "菜单12"}]}
        - {label: '下拉2', items: [{href: "/forum/topics/1", label: "菜单22"}, {href: "/forum/topics/1", label: "菜单22"}]}
      footer:
        - {href: "/forum/topics/1", label: "隐私"}
        - {href: "/forum/topics/1", label: "条款"}
        - {href: "/forum/topics/1", label: "团队"}
  en:
    nav:
      header:
        - {label: 'Dropdown 1', items: [{href: "/forum/topics/1", label: "Menu 11"}, {href: "/forum/topics/1", label: "Menu 12"}]}
        - {label: 'Dropdown 2', items: [{href: "/forum/topics/1", label: "Menu 22"}, {href: "/forum/topics/1", label: "Menu 22"}]}
      footer:
        - {href: "/forum/topics/1", label: "Privacy"}
        - {href: "/forum/topics/1", label: "Terms"}
        - {href: "/forum/topics/1", label: "Teams"}

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
